title: Public Tutorial
description: A tutorial page with images and text
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

# Optional settings
logo: images/logo.png       # put your logo in images folder (optional)
header:
  show: true
