title: Public Tutorial
description: A tutorial page with images and text

# Only use remote_theme
remote_theme: "pmarsceill/just-the-docs"

# Enable remote theme plugin
plugins:
  - jekyll-remote-theme

# Optional settings
logo: images/logo.png   # put your logo in images folder (optional)
header:
  show: true

show_toc: true


